<?php

namespace GST\ImmobilierBundle\Repository;

/**
 * BienRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BienRepository extends \Doctrine\ORM\EntityRepository
{
    public function findBienByValues($localite, $typebien){ 
        
        $query = $this->getEntityManager()->createQuery(
                'SELECT b FROM GSTImmobilierBundle:Bien b 
                    WHERE 
                    b.localite in (SELECT l.id FROM GSTImmobilierBundle:Localite l WHERE l.libelleloca like :localite ) 
                    AND 
                    b.typebien in (SELECT t.id FROM GSTImmobilierBundle:Typebien t WHERE t.libelletype like :typebien )'
        )->setParameter(
            'localite', $localite
        )->setParameter(
            'typebien', $typebien
        );

        return $query->execute();
    }
    public function findbien($localite=0,$typebien=0,$prixLoc=0){

    }
}
