<?php

namespace GST\ImmobilierBundle\Repository;

/**
 * BienProRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BienProRepository extends \Doctrine\ORM\EntityRepository
{
}
