<?php

namespace GST\ImmobilierBundle\Repository;

/**
 * Bien_proRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Bien_proRepository extends \Doctrine\ORM\EntityRepository
{
}
