<?php

namespace GST\ImmobilierBundle\Repository;

/**
 * ImageproRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImageproRepository extends \Doctrine\ORM\EntityRepository
{
}
