<?php

namespace GST\ImmobilierBundle\Repository;

/**
 * Reserve_proRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Reserve_proRepository extends \Doctrine\ORM\EntityRepository
{
}
