<?php

namespace Proxies\__CG__\GST\ImmobilierBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class BienPro extends \GST\ImmobilierBundle\Entity\BienPro implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'GST\\ImmobilierBundle\\Entity\\BienPro' . "\0" . 'id', '' . "\0" . 'GST\\ImmobilierBundle\\Entity\\BienPro' . "\0" . 'nom', '' . "\0" . 'GST\\ImmobilierBundle\\Entity\\BienPro' . "\0" . 'description', '' . "\0" . 'GST\\ImmobilierBundle\\Entity\\BienPro' . "\0" . 'montantvoulu', '' . "\0" . 'GST\\ImmobilierBundle\\Entity\\BienPro' . "\0" . 'etat', '' . "\0" . 'GST\\ImmobilierBundle\\Entity\\BienPro' . "\0" . 'idparent', '' . "\0" . 'GST\\ImmobilierBundle\\Entity\\BienPro' . "\0" . 'localite', '' . "\0" . 'GST\\ImmobilierBundle\\Entity\\BienPro' . "\0" . 'typebien', '' . "\0" . 'GST\\ImmobilierBundle\\Entity\\BienPro' . "\0" . 'imagepros', '' . "\0" . 'GST\\ImmobilierBundle\\Entity\\BienPro' . "\0" . 'reserve_pros', '' . "\0" . 'GST\\ImmobilierBundle\\Entity\\BienPro' . "\0" . 'contrat_pros', '' . "\0" . 'GST\\ImmobilierBundle\\Entity\\BienPro' . "\0" . 'proprietaire'];
        }

        return ['__isInitialized__', '' . "\0" . 'GST\\ImmobilierBundle\\Entity\\BienPro' . "\0" . 'id', '' . "\0" . 'GST\\ImmobilierBundle\\Entity\\BienPro' . "\0" . 'nom', '' . "\0" . 'GST\\ImmobilierBundle\\Entity\\BienPro' . "\0" . 'description', '' . "\0" . 'GST\\ImmobilierBundle\\Entity\\BienPro' . "\0" . 'montantvoulu', '' . "\0" . 'GST\\ImmobilierBundle\\Entity\\BienPro' . "\0" . 'etat', '' . "\0" . 'GST\\ImmobilierBundle\\Entity\\BienPro' . "\0" . 'idparent', '' . "\0" . 'GST\\ImmobilierBundle\\Entity\\BienPro' . "\0" . 'localite', '' . "\0" . 'GST\\ImmobilierBundle\\Entity\\BienPro' . "\0" . 'typebien', '' . "\0" . 'GST\\ImmobilierBundle\\Entity\\BienPro' . "\0" . 'imagepros', '' . "\0" . 'GST\\ImmobilierBundle\\Entity\\BienPro' . "\0" . 'reserve_pros', '' . "\0" . 'GST\\ImmobilierBundle\\Entity\\BienPro' . "\0" . 'contrat_pros', '' . "\0" . 'GST\\ImmobilierBundle\\Entity\\BienPro' . "\0" . 'proprietaire'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (BienPro $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setNom($nom)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNom', [$nom]);

        return parent::setNom($nom);
    }

    /**
     * {@inheritDoc}
     */
    public function getNom()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNom', []);

        return parent::getNom();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescription($description)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescription', [$description]);

        return parent::setDescription($description);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescription()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescription', []);

        return parent::getDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setMontantvoulu($montantvoulu)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMontantvoulu', [$montantvoulu]);

        return parent::setMontantvoulu($montantvoulu);
    }

    /**
     * {@inheritDoc}
     */
    public function getMontantvoulu()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMontantvoulu', []);

        return parent::getMontantvoulu();
    }

    /**
     * {@inheritDoc}
     */
    public function setEtat($etat)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEtat', [$etat]);

        return parent::setEtat($etat);
    }

    /**
     * {@inheritDoc}
     */
    public function getEtat()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEtat', []);

        return parent::getEtat();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdparent($idparent)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdparent', [$idparent]);

        return parent::setIdparent($idparent);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdparent()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdparent', []);

        return parent::getIdparent();
    }

    /**
     * {@inheritDoc}
     */
    public function setLocalite(\GST\ImmobilierBundle\Entity\Localite $localite = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLocalite', [$localite]);

        return parent::setLocalite($localite);
    }

    /**
     * {@inheritDoc}
     */
    public function getLocalite()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLocalite', []);

        return parent::getLocalite();
    }

    /**
     * {@inheritDoc}
     */
    public function setTypebien(\GST\ImmobilierBundle\Entity\Typebien $typebien = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTypebien', [$typebien]);

        return parent::setTypebien($typebien);
    }

    /**
     * {@inheritDoc}
     */
    public function getTypebien()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTypebien', []);

        return parent::getTypebien();
    }

    /**
     * {@inheritDoc}
     */
    public function addReservePro(\GST\ImmobilierBundle\Entity\Reserve_pro $reservePro)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addReservePro', [$reservePro]);

        return parent::addReservePro($reservePro);
    }

    /**
     * {@inheritDoc}
     */
    public function removeReservePro(\GST\ImmobilierBundle\Entity\Reserve_pro $reservePro)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeReservePro', [$reservePro]);

        return parent::removeReservePro($reservePro);
    }

    /**
     * {@inheritDoc}
     */
    public function getReservePros()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getReservePros', []);

        return parent::getReservePros();
    }

    /**
     * {@inheritDoc}
     */
    public function addContratPro(\GST\ImmobilierBundle\Entity\Contrat_pro $contratPro)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addContratPro', [$contratPro]);

        return parent::addContratPro($contratPro);
    }

    /**
     * {@inheritDoc}
     */
    public function removeContratPro(\GST\ImmobilierBundle\Entity\Contrat_pro $contratPro)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeContratPro', [$contratPro]);

        return parent::removeContratPro($contratPro);
    }

    /**
     * {@inheritDoc}
     */
    public function getContratPros()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getContratPros', []);

        return parent::getContratPros();
    }

    /**
     * {@inheritDoc}
     */
    public function setProprietaire(\GST\ImmobilierBundle\Entity\Proprietaire $proprietaire)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProprietaire', [$proprietaire]);

        return parent::setProprietaire($proprietaire);
    }

    /**
     * {@inheritDoc}
     */
    public function getProprietaire()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProprietaire', []);

        return parent::getProprietaire();
    }

    /**
     * {@inheritDoc}
     */
    public function addImagepro(\GST\ImmobilierBundle\Entity\Imagepro $imagepro)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addImagepro', [$imagepro]);

        return parent::addImagepro($imagepro);
    }

    /**
     * {@inheritDoc}
     */
    public function removeImagepro(\GST\ImmobilierBundle\Entity\Imagepro $imagepro)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeImagepro', [$imagepro]);

        return parent::removeImagepro($imagepro);
    }

    /**
     * {@inheritDoc}
     */
    public function getImagepros()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImagepros', []);

        return parent::getImagepros();
    }

}
