<?php

namespace Proxies\__CG__\GST\ImmobilierBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Bien extends \GST\ImmobilierBundle\Entity\Bien implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'GST\\ImmobilierBundle\\Entity\\Bien' . "\0" . 'id', '' . "\0" . 'GST\\ImmobilierBundle\\Entity\\Bien' . "\0" . 'nombien', '' . "\0" . 'GST\\ImmobilierBundle\\Entity\\Bien' . "\0" . 'description', '' . "\0" . 'GST\\ImmobilierBundle\\Entity\\Bien' . "\0" . 'prix_loc', '' . "\0" . 'GST\\ImmobilierBundle\\Entity\\Bien' . "\0" . 'etat', '' . "\0" . 'GST\\ImmobilierBundle\\Entity\\Bien' . "\0" . 'idparentbien', '' . "\0" . 'GST\\ImmobilierBundle\\Entity\\Bien' . "\0" . 'localite', '' . "\0" . 'GST\\ImmobilierBundle\\Entity\\Bien' . "\0" . 'typebien', '' . "\0" . 'GST\\ImmobilierBundle\\Entity\\Bien' . "\0" . 'images', '' . "\0" . 'GST\\ImmobilierBundle\\Entity\\Bien' . "\0" . 'reservations'];
        }

        return ['__isInitialized__', '' . "\0" . 'GST\\ImmobilierBundle\\Entity\\Bien' . "\0" . 'id', '' . "\0" . 'GST\\ImmobilierBundle\\Entity\\Bien' . "\0" . 'nombien', '' . "\0" . 'GST\\ImmobilierBundle\\Entity\\Bien' . "\0" . 'description', '' . "\0" . 'GST\\ImmobilierBundle\\Entity\\Bien' . "\0" . 'prix_loc', '' . "\0" . 'GST\\ImmobilierBundle\\Entity\\Bien' . "\0" . 'etat', '' . "\0" . 'GST\\ImmobilierBundle\\Entity\\Bien' . "\0" . 'idparentbien', '' . "\0" . 'GST\\ImmobilierBundle\\Entity\\Bien' . "\0" . 'localite', '' . "\0" . 'GST\\ImmobilierBundle\\Entity\\Bien' . "\0" . 'typebien', '' . "\0" . 'GST\\ImmobilierBundle\\Entity\\Bien' . "\0" . 'images', '' . "\0" . 'GST\\ImmobilierBundle\\Entity\\Bien' . "\0" . 'reservations'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Bien $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setNombien($nombien)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNombien', [$nombien]);

        return parent::setNombien($nombien);
    }

    /**
     * {@inheritDoc}
     */
    public function getNombien()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNombien', []);

        return parent::getNombien();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescription($description)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescription', [$description]);

        return parent::setDescription($description);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescription()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescription', []);

        return parent::getDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrix_loc($prix_loc)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrix_loc', [$prix_loc]);

        return parent::setPrix_loc($prix_loc);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrix_loc()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrix_loc', []);

        return parent::getPrix_loc();
    }

    /**
     * {@inheritDoc}
     */
    public function setEtat($etat)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEtat', [$etat]);

        return parent::setEtat($etat);
    }

    /**
     * {@inheritDoc}
     */
    public function getEtat()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEtat', []);

        return parent::getEtat();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdparentbien($idparentbien)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdparentbien', [$idparentbien]);

        return parent::setIdparentbien($idparentbien);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdparentbien()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdparentbien', []);

        return parent::getIdparentbien();
    }

    /**
     * {@inheritDoc}
     */
    public function setLocalite(\GST\ImmobilierBundle\Entity\Localite $localite = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLocalite', [$localite]);

        return parent::setLocalite($localite);
    }

    /**
     * {@inheritDoc}
     */
    public function getLocalite()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLocalite', []);

        return parent::getLocalite();
    }

    /**
     * {@inheritDoc}
     */
    public function setTypebien(\GST\ImmobilierBundle\Entity\Typebien $typebien = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTypebien', [$typebien]);

        return parent::setTypebien($typebien);
    }

    /**
     * {@inheritDoc}
     */
    public function getTypebien()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTypebien', []);

        return parent::getTypebien();
    }

    /**
     * {@inheritDoc}
     */
    public function addImage(\GST\ImmobilierBundle\Entity\Image $image)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addImage', [$image]);

        return parent::addImage($image);
    }

    /**
     * {@inheritDoc}
     */
    public function removeImage(\GST\ImmobilierBundle\Entity\Image $image)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeImage', [$image]);

        return parent::removeImage($image);
    }

    /**
     * {@inheritDoc}
     */
    public function getImages()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImages', []);

        return parent::getImages();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrixLoc($prixLoc)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrixLoc', [$prixLoc]);

        return parent::setPrixLoc($prixLoc);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrixLoc()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrixLoc', []);

        return parent::getPrixLoc();
    }

    /**
     * {@inheritDoc}
     */
    public function addReservation(\GST\ImmobilierBundle\Entity\Image $reservation)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addReservation', [$reservation]);

        return parent::addReservation($reservation);
    }

    /**
     * {@inheritDoc}
     */
    public function removeReservation(\GST\ImmobilierBundle\Entity\Image $reservation)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeReservation', [$reservation]);

        return parent::removeReservation($reservation);
    }

    /**
     * {@inheritDoc}
     */
    public function getReservations()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getReservations', []);

        return parent::getReservations();
    }

}
